name: cron

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running manually"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -U pipenv
      - run: pipenv install --skip-lock
      - run: pipenv run python list2md.multiprocess.py --token ${{ secrets.GITHUB_TOKEN }}
      - name: Add & Commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'kkweon@gmail.com'
          git commit -am "GitHub Cron Workflow Commit"
          git push
